language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - Fortran_COMPILER='gfortran'
      script:
        - cmake  -DHEPMC3_ENABLE_ROOTIO=OFF -DHEPMC3_BUILD_EXAMPLES=ON -DHEPMC3_ENABLE_TEST=ON CMakeLists.txt
        - cmake --build .    
        - ctest --output-on-failure  
    - os: osx
      compiler: gcc
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - Fortran_COMPILER='gfortran'
      script:
        - cmake  -DHEPMC3_ENABLE_ROOTIO=OFF -DHEPMC3_BUILD_EXAMPLES=ON -DHEPMC3_ENABLE_TEST=ON CMakeLists.txt
        - cmake --build .    
        - ctest --output-on-failure
    - os: osx
      compiler: clang
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
        - Fortran_COMPILER='gfortran'
      script:
        - cmake  -DHEPMC3_ENABLE_ROOTIO=OFF -DHEPMC3_BUILD_EXAMPLES=ON -DHEPMC3_ENABLE_TEST=ON CMakeLists.txt
        - cmake --build .    
        - ctest --output-on-failure
    - os: windows
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script:
        - export PATH=$CMAKE_PATH:$PATH
        - cmake  -DHEPMC3_ENABLE_ROOTIO=OFF -DHEPMC3_BUILD_EXAMPLES=ON -DHEPMC3_ENABLE_TEST=ON  -Thost=x64 -A x64  CMakeLists.txt
        - cmake --build .      
 #       - ctest --output-on-failure
 #       - cat Testing/Temporary/*

